import { Lead, Car, ChatHistoryRecord } from '../types';

export const MOCK_CARS: Car[] = [
  {
    id: 'c1111111-1111-4111-8111-111111111111',
    brand: 'Volvo',
    model: 'V40',
    version: '2.0 T4 Kinetic',
    year: 2018,
    km: 68000,
    color: 'Cinza Metálico',
    price: 88900,
    accepts_trade: true,
    financing_available: true,
    fuel: 'gasolina',
    transmission: 'automático',
    body_type: 'hatch',
    avg_consumption_city: 9.8,
    avg_consumption_road: 13.5,
    monthly_cost_estimate: 1850.00,
    notes: 'Excelente estado de conservação, histórico completo de revisões, pacote City Safety.',
    active: true,
    created_at: '2026-08-10T10:00:00Z',
    updated_at: '2026-08-10T10:00:00Z'
  },
  {
    id: 'c2222222-2222-4222-8222-222222222222',
    brand: 'Toyota',
    model: 'Corolla Cross',
    version: 'XRX Hybrid 1.8',
    year: 2023,
    km: 24000,
    color: 'Branco Pérola',
    price: 189900,
    accepts_trade: true,
    financing_available: true,
    fuel: 'híbrido',
    transmission: 'cvt',
    body_type: 'suv',
    avg_consumption_city: 17.8,
    avg_consumption_road: 14.7,
    monthly_cost_estimate: 1250.00,
    notes: 'Garantia de fábrica até 2028, teto solar, Toyota Safety Sense completo.',
    active: true,
    created_at: '2026-08-12T14:30:00Z',
    updated_at: '2026-08-12T14:30:00Z'
  },
  {
    id: 'c3333333-3333-4333-8333-333333333333',
    brand: 'Jeep',
    model: 'Compass',
    version: 'Longitude T270 1.3 Turbo',
    year: 2024,
    km: 12000,
    color: 'Preto Carbon',
    price: 179900,
    accepts_trade: true,
    financing_available: true,
    fuel: 'flex',
    transmission: 'automático',
    body_type: 'suv',
    avg_consumption_city: 10.5,
    avg_consumption_road: 13.2,
    monthly_cost_estimate: 1980.00,
    notes: 'Único dono, multimídia 10.1", bancos em couro, faróis Full LED.',
    active: true,
    created_at: '2026-08-13T09:15:00Z',
    updated_at: '2026-08-13T09:15:00Z'
  },
  {
    id: 'c4444444-4444-4444-8444-444444444444',
    brand: 'BYD',
    model: 'Dolphin',
    version: 'GS 100% Elétrico',
    year: 2024,
    km: 8500,
    color: 'Azul Afterglow',
    price: 148900,
    accepts_trade: true,
    financing_available: true,
    fuel: 'elétrico',
    transmission: 'automático',
    body_type: 'hatch',
    avg_consumption_city: 29.1,
    avg_consumption_road: 26.5,
    monthly_cost_estimate: 420.00,
    notes: 'Bateria Blade com 8 anos de garantia, câmera 360, tela giratória de 12.8 pol.',
    active: true,
    created_at: '2026-08-14T11:00:00Z',
    updated_at: '2026-08-14T11:00:00Z'
  },
  {
    id: 'c5555555-5555-4555-8555-555555555555',
    brand: 'Volkswagen',
    model: 'Golf Variant',
    version: '1.4 TSI Highline',
    year: 2017,
    km: 79000,
    color: 'Prata Tungstênio',
    price: 89900,
    accepts_trade: true,
    financing_available: true,
    fuel: 'gasolina',
    transmission: 'automático',
    body_type: 'minivan',
    avg_consumption_city: 11.2,
    avg_consumption_road: 14.8,
    monthly_cost_estimate: 1780.00,
    notes: 'Perua clássica para quem busca dinâmica e 605 litros de porta-malas.',
    active: true,
    created_at: '2026-08-11T16:20:00Z',
    updated_at: '2026-08-11T16:20:00Z'
  }
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'l1111111-1111-4111-8111-111111111111',
    phone: '5527998877665',
    name: 'Gabriel',
    city: 'Serra',
    stage: 'interviewing',
    lead_quality: 'warm',
    profile_data: {
      city: 'Serra',
      name: 'Gabriel',
      terrain: 'mixed',
      has_pets: null,
      min_year: null,
      pet_size: null,
      use_type: 'PF',
      has_cargo: false,
      mapa_top3: ['conforto', 'segurança', 'tecnologia'],
      monthly_km: 1000,
      passengers: 1,
      trade_in_km: null,
      accepts_used: true,
      has_children: false,
      has_trade_in: true,
      payment_type: null,
      total_budget: 90000,
      transmission: 'no_preference',
      children_ages: null,
      trade_in_year: null,
      needs_car_seat: null,
      trade_in_model: 'Palio Weekend',
      body_preference: ['perua'],
      brand_blacklist: null,
      brand_whitelist: ['Volvo'],
      lifestyle_notes: null,
      interested_in_ev: null,
      max_monthly_cost: 2000,
      ownership_period_years: null
    },
    mapa_ranking: ['conforto', 'segurança', 'tecnologia'],
    ctm_estimate: 1850.00,
    ownership_period_years: 3,
    ctp_estimate: 72000.00,
    consultant_notes: 'Cliente busca troca da Weekend por modelo com excelente segurança e conforto. Demonstrou grande apreço por Volvo.',
    created_at: '2026-08-14T20:10:00Z',
    updated_at: '2026-08-14T21:40:00Z'
  },
  {
    id: 'l2222222-2222-4222-8222-222222222222',
    phone: '5511987654321',
    name: 'Rodrigo Mendonça',
    city: 'São Paulo',
    stage: 'handoff_requested',
    lead_quality: 'hot',
    profile_data: {
      city: 'São Paulo',
      name: 'Rodrigo',
      terrain: 'urban',
      has_pets: false,
      min_year: 2022,
      pet_size: null,
      use_type: 'PF',
      has_cargo: true,
      mapa_top3: ['economia', 'espaço', 'segurança'],
      monthly_km: 1200,
      passengers: 4,
      trade_in_km: 72000,
      accepts_used: true,
      has_children: true,
      has_trade_in: true,
      payment_type: 'financing',
      total_budget: 195000,
      transmission: 'automático',
      children_ages: '4 e 7 anos',
      trade_in_year: 2017,
      needs_car_seat: true,
      trade_in_model: 'Honda Civic',
      body_preference: ['suv'],
      brand_blacklist: null,
      brand_whitelist: ['Toyota', 'Jeep'],
      lifestyle_notes: 'Roda 40km/dia na marginal e viaja com a família aos finais de semana',
      interested_in_ev: false,
      max_monthly_cost: 2500,
      ownership_period_years: 4
    },
    mapa_ranking: ['economia', 'espaço', 'segurança'],
    ctm_estimate: 1450.00,
    ownership_period_years: 4,
    ctp_estimate: 98000.00,
    consultant_notes: 'Solicitou agendamento de test-drive para o Corolla Cross XRX Hybrid no sábado.',
    created_at: '2026-08-14T14:32:00Z',
    updated_at: '2026-08-14T19:40:00Z'
  },
  {
    id: 'l3333333-3333-4333-8333-333333333333',
    phone: '5521991238877',
    name: 'Camila Vasconcelos',
    city: 'Rio de Janeiro',
    stage: 'recommendation_sent',
    lead_quality: 'warm',
    profile_data: {
      city: 'Rio de Janeiro',
      name: 'Camila',
      terrain: 'urban',
      has_pets: null,
      min_year: 2023,
      pet_size: null,
      use_type: 'PF',
      has_cargo: false,
      mapa_top3: ['tecnologia', 'economia', 'praticidade'],
      monthly_km: 800,
      passengers: 2,
      trade_in_km: 45000,
      accepts_used: true,
      has_children: false,
      has_trade_in: true,
      payment_type: 'cash',
      total_budget: 155000,
      transmission: 'automático',
      children_ages: null,
      trade_in_year: 2021,
      needs_car_seat: false,
      trade_in_model: 'Chevrolet Onix',
      body_preference: ['hatch'],
      brand_blacklist: null,
      brand_whitelist: ['BYD'],
      lifestyle_notes: 'Garagem com ponto de recarga, uso 90% na Zona Sul',
      interested_in_ev: true,
      max_monthly_cost: 800,
      ownership_period_years: 3
    },
    mapa_ranking: ['tecnologia', 'economia', 'praticidade'],
    ctm_estimate: 480.00,
    ownership_period_years: 3,
    ctp_estimate: 32000.00,
    consultant_notes: 'Dossiê do Dolphin enviado. Avaliando custos de seguro.',
    created_at: '2026-08-14T16:15:00Z',
    updated_at: '2026-08-14T18:22:00Z'
  },
  {
    id: 'l4444444-4444-4444-8444-444444444444',
    phone: '5531973441122',
    name: 'Eduardo Silveira',
    city: 'Belo Horizonte',
    stage: 'profile_confirmed',
    lead_quality: 'hot',
    profile_data: {
      city: 'Belo Horizonte',
      name: 'Eduardo',
      terrain: 'mixed',
      has_pets: true,
      min_year: 2023,
      pet_size: 'médio',
      use_type: 'PF',
      has_cargo: true,
      mapa_top3: ['potência', 'espaço', 'conforto'],
      monthly_km: 1500,
      passengers: 3,
      trade_in_km: 60000,
      accepts_used: true,
      has_children: true,
      has_trade_in: true,
      payment_type: 'financing',
      total_budget: 220000,
      transmission: 'automático',
      children_ages: '10 anos',
      trade_in_year: 2019,
      needs_car_seat: false,
      trade_in_model: 'Jeep Renegade',
      body_preference: ['suv'],
      brand_blacklist: null,
      brand_whitelist: ['GWM', 'Jeep'],
      lifestyle_notes: 'Viagens frequentes para interior com subidas de serra',
      interested_in_ev: false,
      max_monthly_cost: 3000,
      ownership_period_years: 3
    },
    mapa_ranking: ['potência', 'espaço', 'conforto'],
    ctm_estimate: 2100.00,
    ownership_period_years: 3,
    ctp_estimate: 110000.00,
    consultant_notes: 'Em dúvida entre Haval H6 e Compass T270. Prioriza torque em subidas.',
    created_at: '2026-08-14T17:05:00Z',
    updated_at: '2026-08-14T20:10:00Z'
  }
];

export const MOCK_CHAT_HISTORY: ChatHistoryRecord[] = [
  // Sessão Gabriel (5527998877665)
  {
    id: 1,
    session_id: '5527998877665',
    message: {
      type: 'human',
      content: 'Olá! Sou o Gabriel, moro em Serra no ES e estou querendo trocar de carro.'
    },
    created_at: '2026-08-14T20:10:00Z'
  },
  {
    id: 2,
    session_id: '5527998877665',
    message: {
      type: 'ai',
      content: 'Prazer, Gabriel! A Grande Vitória e a Serra são ótimas para rodar, mas tem suas particularidades de trânsito na BR-101 e subidas.\n\n---\n\nO carro que você está procurando vai ser para uso pessoal no dia a dia ou você precisa para trabalho/família?\n\n---\n\n[[STAGE:interviewing|QUALITY:warm]]',
      tool_calls: [],
      additional_kwargs: {},
      response_metadata: {},
      invalid_tool_calls: []
    },
    created_at: '2026-08-14T20:10:30Z'
  },
  {
    id: 3,
    session_id: '5527998877665',
    message: {
      type: 'human',
      content: 'Uso pessoal (PF). Tenho uma Palio Weekend hoje e gosto muito de peruas e espaço, mas queria algo mais moderno e seguro, até uns 90 mil reais. Gosto bastante da marca Volvo também.'
    },
    created_at: '2026-08-14T20:12:00Z'
  },
  {
    id: 4,
    session_id: '5527998877665',
    message: {
      type: 'ai',
      content: 'Entendido perfeitamente, Gabriel! Quem vem de uma perua como a Weekend valoriza muito dirigibilidade e conforto de rodagem sem a altura exagerada de um SUV.\n\nNa faixa de R$ 90.000 com o seu foco em **Conforto, Segurança e Tecnologia** (seu MAPA Top 3), temos uma opção fantástica no estoque: o **Volvo V40 2.0 Turbo (R$ 88.900)**, equipado com o sistema City Safety de frenagem autônoma e acabamento sueco de primeira linha.\n\nVocê aceita dar sua Weekend na troca como entrada?\n\n---\n\n[[STAGE:interviewing|QUALITY:warm]]',
      tool_calls: [],
      additional_kwargs: {},
      response_metadata: {},
      invalid_tool_calls: []
    },
    created_at: '2026-08-14T20:13:15Z'
  },

  // Sessão Rodrigo (5511987654321)
  {
    id: 5,
    session_id: '5511987654321',
    message: {
      type: 'human',
      content: 'Boa tarde! Preciso de um SUV para a família de até 195 mil.'
    },
    created_at: '2026-08-14T14:32:00Z'
  },
  {
    id: 6,
    session_id: '5511987654321',
    message: {
      type: 'ai',
      content: 'Olá Rodrigo! Para acomodar com segurança sua família e ter baixo custo operacional em São Paulo, o **Toyota Corolla Cross Hybrid (R$ 189.900)** entrega 17,8 km/l na cidade e isenção de rodízio.\n\nPosso agendar um test-drive para você e sua família?\n\n---\n\n[[STAGE:recommendation_sent|QUALITY:hot]]',
      tool_calls: [],
      additional_kwargs: {},
      response_metadata: {},
      invalid_tool_calls: []
    },
    created_at: '2026-08-14T14:35:00Z'
  },
  {
    id: 7,
    session_id: '5511987654321',
    message: {
      type: 'human',
      content: 'Quero agendar sim! Sábado pela manhã seria perfeito.'
    },
    created_at: '2026-08-14T19:38:00Z'
  },
  {
    id: 8,
    session_id: '5511987654321',
    message: {
      type: 'ai',
      content: 'Excelente Rodrigo! Solicitei o encaminhamento para o consultor da concessionária preparar o Corolla Cross Hybrid no sábado às 10h30. Nos vemos lá!\n\n---\n\n[[STAGE:handoff_requested|QUALITY:hot]]',
      tool_calls: [],
      additional_kwargs: {},
      response_metadata: {},
      invalid_tool_calls: []
    },
    created_at: '2026-08-14T19:40:00Z'
  }
];
